### ISSUE TITLE
flamethrower crashes

### ISSUE THREAD

**Issue by timurb** [blakesmith/flamethrower#15]
I'm connecting to flamethrower using irssi with loglevel DEBUG set:

admin2% bin/flamethrower -c ~/flamethrower.yml
I, [2011-07-16T16:31:08.053168 #24470]  INFO -- : Flamethrower started at 0.0.0.0:6667 on domain XXX.campfirenow.com
D, [2011-07-16T16:31:16.691742 #24470] DEBUG -- : << NICK erthad
D, [2011-07-16T16:31:16.692081 #24470] DEBUG -- : >> :erthad 375 erthad :MOTD
D, [2011-07-16T16:31:16.692162 #24470] DEBUG -- : >> :erthad 372 erthad :Welcome to Flamethrower
D, [2011-07-16T16:31:16.692228 #24470] DEBUG -- : >> :erthad 372 erthad :Fetching channel list from campfire...
D, [2011-07-16T16:31:16.692297 #24470] DEBUG -- : Sending GET /rooms.json with no JSON
D, [2011-07-16T16:31:16.694469 #24470] DEBUG -- : Sending GET /users/me.json with no JSON
D, [2011-07-16T16:31:16.695395 #24470] DEBUG -- : << USER erthad erthad localhost :Unknown
D, [2011-07-16T16:31:16.695909 #24470] DEBUG -- : >> :erthad 221 erthad +i
D, [2011-07-16T16:31:16.695987 #24470] DEBUG -- : << MODE erthad +i
D, [2011-07-16T16:31:17.430293 #24470] DEBUG -- : >> :erthad 372 erthad :Active channels:
D, [2011-07-16T16:31:17.430401 #24470] DEBUG -- : >> :erthad 372 erthad :#ops_and_releases - No topic
D, [2011-07-16T16:31:17.430468 #24470] DEBUG -- : >> :erthad 376 erthad :End of channel list /MOTD
D, [2011-07-16T16:31:17.454127 #24470] DEBUG -- : >> :erthad NICK Timur_Batyrshin
D, [2011-07-16T16:31:26.861142 #24470] DEBUG -- : << USER timurb admin2 localhost :purple
D, [2011-07-16T16:31:26.861692 #24470] DEBUG -- : >> :admin2 375 timurb :MOTD
D, [2011-07-16T16:31:26.861779 #24470] DEBUG -- : >> :admin2 372 timurb :Welcome to Flamethrower
D, [2011-07-16T16:31:26.861847 #24470] DEBUG -- : >> :admin2 372 timurb :Fetching channel list from campfire...
D, [2011-07-16T16:31:26.861923 #24470] DEBUG -- : Sending GET /rooms.json with no JSON
D, [2011-07-16T16:31:26.862877 #24470] DEBUG -- : Sending GET /users/me.json with no JSON
D, [2011-07-16T16:31:26.863720 #24470] DEBUG -- : << NICK timurb
D, [2011-07-16T16:31:27.613452 #24470] DEBUG -- : >> :admin2 372 timurb :Active channels:
D, [2011-07-16T16:31:27.613604 #24470] DEBUG -- : >> :admin2 372 timurb :#ops_and_releases - No topic
D, [2011-07-16T16:31:27.613673 #24470] DEBUG -- : >> :admin2 376 timurb :End of channel list /MOTD
D, [2011-07-16T16:31:27.631653 #24470] DEBUG -- : >> :timurb NICK Timur_Batyrshin
./bin/../lib/flamethrower/dispatcher.rb:89:in `handle_away': undefined method`empty?' for nil:NilClass (NoMethodError)
    from ./bin/../lib/flamethrower/dispatcher.rb:11:in `send'
    from ./bin/../lib/flamethrower/dispatcher.rb:11:in`handle_message'
    from ./bin/../lib/flamethrower/connection.rb:28:in `receive_data'
    from ./bin/../lib/flamethrower/connection.rb:27:in`each'
    from ./bin/../lib/flamethrower/connection.rb:27:in `receive_data'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from ./bin/../lib/flamethrower/server/event_server.rb:42:in`start'
    from bin/flamethrower:71
admin2%

**Comment by blakesmith** [comment]
Was out for the weekend so just seeing this now. I'll look into this shortly. :-)

**Comment by blakesmith** [comment]
Can you pull latest from source, install the gem and repost your stack-trace after trying to connect? I made a change that will allow me to see the exact IRC command that crashed the daemon.

```
git clone git://github.com/blakesmith/flamethrower.git
cd flamethrower
gem build flamethrower.gemspec
gem install flamethrower-0.3.1.gem
```

Thanks!

**Comment by timurb** [comment]
I've made a test with a plain telnet command and it seems that AWAY command with no parameters crashes the flamethrower:

admin2% flamethrower -c ~/flamethrower.yml
I, [2011-07-20T10:06:42.759521 #24388]  INFO -- : Flamethrower started at 0.0.0.0:6667 on domain XXX.campfirenow.com
D, [2011-07-20T10:06:58.443008 #24388] DEBUG -- : << USER timurb admin localhost :asd
D, [2011-07-20T10:07:04.214948 #24388] DEBUG -- : << NICK timurb
D, [2011-07-20T10:07:04.215269 #24388] DEBUG -- : >> :admin 375 timurb :MOTD
D, [2011-07-20T10:07:04.215342 #24388] DEBUG -- : >> :admin 372 timurb :Welcome to Flamethrower
D, [2011-07-20T10:07:04.215407 #24388] DEBUG -- : >> :admin 372 timurb :Fetching channel list from campfire...
D, [2011-07-20T10:07:04.215477 #24388] DEBUG -- : Sending GET /rooms.json with no JSON
D, [2011-07-20T10:07:04.287430 #24388] DEBUG -- : Sending GET /users/me.json with no JSON
D, [2011-07-20T10:07:05.028763 #24388] DEBUG -- : >> :admin 372 timurb :Active channels:
D, [2011-07-20T10:07:05.028871 #24388] DEBUG -- : >> :admin 372 timurb :#ops_and_releases - No topic
D, [2011-07-20T10:07:05.028938 #24388] DEBUG -- : >> :admin 376 timurb :End of channel list /MOTD
D, [2011-07-20T10:07:05.057792 #24388] DEBUG -- : >> :timurb NICK Timur_Batyrshin
D, [2011-07-20T10:07:11.850969 #24388] DEBUG -- : << AWAY :I'm away
D, [2011-07-20T10:07:11.851294 #24388] DEBUG -- : >> :campfirenow.com 306 Timur_Batyrshin :You have been marked as being away
D, [2011-07-20T10:07:15.158454 #24388] DEBUG -- : << AWAY :
D, [2011-07-20T10:07:15.158745 #24388] DEBUG -- : >> :campfirenow.com 305 Timur_Batyrshin :You are no longer marked as being away
D, [2011-07-20T10:07:17.966649 #24388] DEBUG -- : << AWAY
/usr/local/rvm/gems/ree-1.8.7-2011.03/gems/flamethrower-0.3.1/bin/../lib/flamethrower/dispatcher.rb:89:in `handle_away': undefined method`empty?' for nil:NilClass (NoMethodError)
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/flamethrower-0.3.1/bin/../lib/flamethrower/dispatcher.rb:11:in `send'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/flamethrower-0.3.1/bin/../lib/flamethrower/dispatcher.rb:11:in`handle_message'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/flamethrower-0.3.1/bin/../lib/flamethrower/connection.rb:29:in `receive_data'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/flamethrower-0.3.1/bin/../lib/flamethrower/connection.rb:27:in`each'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/flamethrower-0.3.1/bin/../lib/flamethrower/connection.rb:27:in `receive_data'
==rest of stack trace skipped==

**Comment by timurb** [comment]
sorry, closed the issue by accident

**Comment by blakesmith** [comment]
Closed here: https://github.com/blakesmith/flamethrower/commit/dbd2759353bb2439698329c5be00f6ab0607d996. Accidentally put the wrong issue number in the commit message.

Thanks for the great bug report. Let me know how it works!

Blake

**Comment by timurb** [comment]
It does not crash now yet pidgin seems not to work with it.

Anyway, thanks for quick fixing!

**Comment by blakesmith** [comment]
Thanks for the report. I've only done flamethrower testing with irssi - perhaps it's time for me to do some debugging with Pidgin. Thanks for the heads up!

**Comment by timurb** [comment]
Just FYI:
Some IRC clients does not work when there is no actual list of channels so you can't join and follow the channel — that is the case with Pidgin.
Kvirc works ok though a bit strange — you have to join channel first and then do /query #channel to send messages through it. As for the rest of clients — I don't remember exactly how they did (or did not) work — I think most of failures were similar to that of pidgin.
